import streamlit as st
import time
import zipfile
import io
from PIL import Image, ImageDraw, ImageOps
import numpy as np
import plotly.graph_objects as go
from datetime import datetime

# --- CONFIGURATION ---
st.set_page_config(
    page_title="NagataGuide",
    page_icon="🦻",
    layout="centered",
    initial_sidebar_state="collapsed"
)

# --- CUSTOM CSS (CLINICAL THEME) ---
# Enforcing Surgical Blue (#2563EB) and Inter font styles
st.markdown("""
    <style>
        /* Import Inter font */
        @import url('https://fonts.googleapis.com/css2?family=Inter:wght@400;600;700&display=swap');

        html, body, [class*="css"]  {
            font-family: 'Inter', sans-serif;
        }

        /* Primary Button Styling */
        div.stButton > button:first-child {
            background-color: #2563EB;
            color: white;
            border-radius: 8px;
            padding: 0.75rem 1.5rem;
            font-weight: 600;
            border: none;
            width: 100%;
        }
        div.stButton > button:first-child:hover {
            background-color: #1D4ED8;
            border: none;
        }

        /* Expander Styling */
        .streamlit-expanderHeader {
            font-weight: 600;
            color: #374151;
        }

        /* Success Message */
        .stAlert {
            background-color: #F0FDF4;
            border: 1px solid #BBF7D0;
            color: #166534;
        }
        
        /* Headers */
        h1, h2, h3 {
            color: #111827;
        }
    </style>
""", unsafe_allow_html=True)

# --- HELPER FUNCTIONS ---

def generate_mock_zip():
    """Generates a real ZIP file in memory with dummy content for the user to download."""
    buffer = io.BytesIO()
    with zipfile.ZipFile(buffer, "w", zipfile.ZIP_DEFLATED) as zip_file:
        # Create dummy STL content
        dummy_stl_content = "solid simulated_ear\n  facet normal 0 0 0\n    outer loop\n      vertex 0 0 0\n      vertex 1 0 0\n      vertex 0 1 0\n    endloop\n  endfacet\nendsolid simulated_ear"
        
        # Add files to zip
        zip_file.writestr("BASE.stl", dummy_stl_content)
        zip_file.writestr("HELIX.stl", dummy_stl_content)
        zip_file.writestr("ANTIHELIX.stl", dummy_stl_content)
        zip_file.writestr("HOLES.stl", dummy_stl_content)
        
        # Add README
        readme_text = """NAGATA GUIDE PRINT INSTRUCTIONS
===============================

1. PRINT SETTINGS:
   - Material: Biocompatible Resin or PLA
   - Layer Height: 0.1mm - 0.2mm
   - Infill: 100%

2. ASSEMBLY ORDER:
   - Step A: Print BASE.stl first (0-2mm height).
   - Step B: Align HELIX.stl and ANTIHELIX.stl on top.
   - Step C: Ensure suture holes (HOLES.stl) are clear.

3. SAFETY:
   - Sterilize using standard autoclaving protocols before surgical use.
   - Verify dimensions against physical anatomy.

Generated by NagataGuide.
"""
        zip_file.writestr("README.txt", readme_text)
        
    buffer.seek(0)
    return buffer

def create_mock_3d_plot():
    """Creates a Plotly mesh that looks somewhat like a curved organic shape."""
    # Generating a torus-like shape to represent an ear structure abstractly
    theta = np.linspace(0, 2*np.pi, 50)
    phi = np.linspace(0, 2*np.pi, 50)
    theta, phi = np.meshgrid(theta, phi)
    c, a = 2, 1
    x = (c + a*np.cos(theta)) * np.cos(phi)
    y = (c + a*np.cos(theta)) * np.sin(phi)
    z = a * np.sin(theta)

    fig = go.Figure(data=[go.Surface(z=z, x=x, y=y, colorscale='Blues', opacity=0.8)])
    fig.update_layout(
        title='3D Guide Preview (Interactive)',
        scene=dict(xaxis=dict(visible=False), yaxis=dict(visible=False), zaxis=dict(visible=False)),
        margin=dict(l=0, r=0, b=0, t=30),
        height=300
    )
    return fig

def create_segmentation_overlay(uploaded_image):
    """Overlays a mock segmentation mask on the uploaded image."""
    img = Image.open(uploaded_image).convert("RGBA")
    # Resize for consistency
    img = img.resize((400, int(400 * img.height / img.width)))
    
    # Create a mask layer
    mask = Image.new('RGBA', img.size, (0,0,0,0))
    draw = ImageDraw.Draw(mask)
    
    # Draw a mock "Ear" shape (ellipse) in the center
    w, h = img.size
    draw.ellipse((w*0.25, h*0.2, w*0.75, h*0.8), fill=(37, 99, 235, 100), outline=(37, 99, 235, 255))
    
    # Composite
    return Image.alpha_composite(img, mask)

# --- APP STATE MANAGEMENT ---
if 'processed' not in st.session_state:
    st.session_state.processed = False
if 'processing_complete' not in st.session_state:
    st.session_state.processing_complete = False

# --- HEADER ---
col1, col2 = st.columns([1, 5])
with col1:
    st.write("# 🦻") # Large Emoji Icon
with col2:
    st.title("NagataGuide")
    st.caption("From 2D Photo to 3D Surgical Guide in One Click")

st.markdown("---")

# --- DEBUG / DEMO CONTROLS (Sidebar for Demo purposes) ---
with st.sidebar:
    st.header("Demo Controls")
    simulate_failure = st.checkbox("Simulate Detection Failure", value=False)
    st.info("Use this to test the error recovery flow described in the PRD.")

# --- STEP 1: UPLOAD & CALIBRATE ---
st.subheader("1. Upload & Calibrate")

uploaded_file = st.file_uploader(
    "Upload patient lateral view (JPG/PNG)", 
    type=["jpg", "png"], 
    help="Ensure neutral background and even lighting."
)

if uploaded_file:
    # Preview Layout
    col_preview, col_settings = st.columns([1, 2])
    
    with col_preview:
        image = Image.open(uploaded_file)
        st.image(image, caption="Uploaded Preview", use_container_width=True)
    
    with col_settings:
        st.write("**Calibration Settings**")
        has_ruler = st.checkbox("☑️ Image includes a physical ruler", value=True)
        
        if not has_ruler:
            with st.container():
                st.info("📏 Manual Calibration Required")
                px_per_mm = st.number_input(
                    "Pixels per millimeter", 
                    min_value=1, max_value=200, value=15,
                    help="Measure a known landmark on screen to determine this value."
                )
                st.caption("Example: If a 10mm mole is 150px wide, enter 15.")

    st.markdown("---")

    # --- STEP 2: PROCESSING ---
    
    # Dynamic CTA Button
    btn_text = "✨ Generate Surgical Guide"
    if st.session_state.processed:
        btn_text = "🔄 Regenerate Guide"

    if st.button(btn_text, type="primary"):
        st.session_state.processed = False
        st.session_state.processing_complete = False
        
        # Live Progress Tracker
        with st.status("Initializing NagataGuide Engine...", expanded=True) as status:
            
            # Phase 1: Detection
            st.write("🔍 Detecting ear anatomy...")
            time.sleep(1.5) # Simulate processing
            
            if simulate_failure:
                status.update(label="❌ Detection Failed", state="error")
                st.error("Could not identify ear structure.")
                col_err, col_tips = st.columns([1, 2])
                with col_err:
                     st.image("https://placehold.co/200x200/FF0000/FFFFFF?text=X", caption="Detection Error")
                with col_tips:
                    st.markdown("""
                    **Try these fixes:**
                    * 📸 Use a full lateral view (side profile).
                    * 💡 Improve lighting (reduce shadows).
                    * 🔄 Center the ear in the frame.
                    """)
                st.stop() # Stop execution here
            
            # Phase 2: Segmentation
            st.write("✂️ Segmenting cartilage and soft tissue...")
            time.sleep(2)
            
            # Phase 3: 3D Modeling
            st.write("🧊 Generating 3D parametric models (Base, Helix, Antihelix)...")
            time.sleep(1.5)
            
            status.update(label="✅ Surgical guide ready! Review below.", state="complete", expanded=False)
            st.session_state.processed = True
            st.session_state.processing_complete = True

    # --- STEP 3: RESULTS & STEP 4: DOWNLOAD ---
    if st.session_state.processing_complete:
        st.success("Analysis complete. Review the surgical preview before downloading the print kit.")
        
        # Tabs for Surgical Logic
        tab1, tab2, tab3 = st.tabs(["1. Surgical Preview", "2. 3D Guides", "3. Print Kit"])
        
        # TAB 1: 2D Validation
        with tab1:
            st.markdown("### Anatomical Segmentation")
            st.caption("Verify that the overlay correctly maps to the patient's anatomy.")
            
            col_orig, col_seg = st.columns(2)
            with col_orig:
                st.image(image, caption="Original Patient Image", use_container_width=True)
            with col_seg:
                # Generate overlay on the fly
                overlay_img = create_segmentation_overlay(uploaded_file)
                st.image(overlay_img, caption="AI Segmentation Mask", use_container_width=True)
            
            st.info("Legend: **Blue Region** = Target Reconstruction Area")

        # TAB 2: 3D Inspection
        with tab2:
            st.markdown("### 3D Model Inspection")
            st.caption("Interactive preview of the generated guide geometry.")
            
            # Plotly Chart
            fig = create_mock_3d_plot()
            st.plotly_chart(fig, use_container_width=True)
            
            col_info1, col_info2, col_info3 = st.columns(3)
            col_info1.metric("Base Thickness", "2.0 mm")
            col_info2.metric("Guide Height", "15.0 mm")
            col_info3.metric("Suture Holes", "12 Count")

        # TAB 3: Download
        with tab3:
            st.markdown("### 📥 Manufacturing Export")
            st.markdown("""
            This package contains all files necessary for 3D printing and surgical planning.
            """)
            
            # Prepare ZIP
            zip_buffer = generate_mock_zip()
            timestamp = datetime.now().strftime("%Y%m%d_%H%M")
            file_name = f"NagataGuide_{timestamp}.zip"
            
            # Primary CTA
            st.download_button(
                label="📥 Download Full Print-Ready Kit (ZIP)",
                data=zip_buffer,
                file_name=file_name,
                mime="application/zip",
                type="primary" # Highlighting this as the main action
            )
            
            with st.expander("Show Kit Contents"):
                st.markdown("""
                * `BASE.stl` - The foundation plate (print first).
                * `HELIX.stl` - Outer rim guide.
                * `ANTIHELIX.stl` - Inner cartilage guide.
                * `HOLES.stl` - Suture marker template.
                * `README.txt` - Clinical parameters and print settings.
                """)

# --- FOOTER ---
st.markdown("---")
st.markdown("""
<div style='text-align: center; color: #6B7280; font-size: 0.8rem;'>
    <strong>⚠️ CLINICAL DISCLAIMER</strong><br>
    NagataGuide is a surgical planning aid. It does not replace clinical judgment, 3D imaging, or intraoperative assessment. 
    Validate all guides against patient anatomy before use. Not a medical device.
</div>
""", unsafe_allow_html=True)
